-- MySQL Script generated by MySQL Workbench
-- Mon Mar 12 21:10:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homestead
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homestead` ;

-- -----------------------------------------------------
-- Schema homestead
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homestead` DEFAULT CHARACTER SET utf8mb4 ;
USE `homestead` ;

-- -----------------------------------------------------
-- Table `homestead`.`ADRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`ADRESS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`ADRESS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pathway_number` VARCHAR(45) NULL DEFAULT NULL,
  `pathway_type` VARCHAR(45) NULL DEFAULT NULL,
  `pathway_name` VARCHAR(100) NULL DEFAULT NULL,
  `complement` VARCHAR(100) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`FOLDERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`FOLDERS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`FOLDERS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `USERS_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`FREQUENCY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`FREQUENCY` ;

CREATE TABLE IF NOT EXISTS `homestead`.`FREQUENCY` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`LISTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`LISTS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`LISTS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `FOLDERS_id` INT(11) NOT NULL DEFAULT '1',
  `PRIORITIES_id` INT(11) NOT NULL DEFAULT '1',
  `USERS_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_start` DATETIME NULL DEFAULT NULL,
  `date_end` DATETIME NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`MESSAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`MESSAGES` ;

CREATE TABLE IF NOT EXISTS `homestead`.`MESSAGES` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `TACHES_id` INT(11) NOT NULL,
  `USERS_id` INT(11) NOT NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `message` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'MESSAGES / USERS_DISCUSSIONS_TACHES';


-- -----------------------------------------------------
-- Table `homestead`.`PEOPLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`PEOPLE` ;

CREATE TABLE IF NOT EXISTS `homestead`.`PEOPLE` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ADRESS_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birth` DATETIME NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`PRIORITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`PRIORITIES` ;

CREATE TABLE IF NOT EXISTS `homestead`.`PRIORITIES` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `color` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `homestead`.`RESET_PASSWORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`RESET_PASSWORD` ;

CREATE TABLE IF NOT EXISTS `homestead`.`RESET_PASSWORD` (
  `id` INT(11) NOT NULL,
  `USERS_id` INT(11) NOT NULL,
  `token` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`STATES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`STATES` ;

CREATE TABLE IF NOT EXISTS `homestead`.`STATES` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COMMENT = 'ETAT de la tache en cours...\nex: en cours, en retard, effect';


-- -----------------------------------------------------
-- Table `homestead`.`STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`STATUS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`STATUS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`TAGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`TAGS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`TAGS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`TAGS_TASKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`TAGS_TASKS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`TAGS_TASKS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `TAGS_id` INT(11) NOT NULL,
  `TASKS_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`TASKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`TASKS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`TASKS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `LISTS_id` INT(11) NOT NULL,
  `USERS_id` INT(11) NOT NULL,
  `PRIORITIES_id` INT(11) NOT NULL DEFAULT '1',
  `FREQUENCY_id` INT(11) NOT NULL DEFAULT '1',
  `USERS_TASKS_id` INT(11) NULL DEFAULT NULL COMMENT 'table faisant le lien entreles collaborateurse et les taches\n',
  `TAGS_TASKS_id` INT(11) NULL DEFAULT NULL,
  `ADRESS_id` INT(11) NULL DEFAULT NULL COMMENT 'lieu de la tache',
  `STATES_id` INT(11) NOT NULL DEFAULT '2',
  `id_parent` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `order` TINYINT(4) NULL DEFAULT NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_start` DATETIME NULL DEFAULT NULL,
  `date_end` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'TACHES ou ELEMENTS';


-- -----------------------------------------------------
-- Table `homestead`.`TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`TYPES` ;

CREATE TABLE IF NOT EXISTS `homestead`.`TYPES` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`USERS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`USERS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `PEOPLE_id` INT(11) NOT NULL,
  `STATUS_id` INT(11) NOT NULL DEFAULT '5' COMMENT 'enligne,occupé, en réunion etc..',
  `TYPES_id` INT(11) NOT NULL DEFAULT '1' COMMENT 'type de compte\nadmin, chef, etc..',
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `token` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homestead`.`USERS_TASKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homestead`.`USERS_TASKS` ;

CREATE TABLE IF NOT EXISTS `homestead`.`USERS_TASKS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `USERS_id` INT(11) NOT NULL,
  `TASKS_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
